# WINDOWS: %APPDATA%\alacritty

[terminal.shell]
program = 'C:\Program Files\PowerShell\7\pwsh.exe'

[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xff9a63"
index = 16

[[colors.indexed_colors]]
color = "0xdb4a4a"
index = 17

[colors.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[cursor]
style = "Block"
unfocused_hollow = true

[colors.normal]
black = "0x15161E"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xc0caf5"

[font]
size = 10

[font.bold]
family = "Cousine Nerd Font Mono"
style = "Regular"

[font.normal]
family = "Cousine Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Control"

[scrolling]
history = 10000
multiplier = 10

[window]
decorations = "full"
opacity = 1

[window.dimensions]
columns = 120
lines = 36

[window.padding]
x = 10
y = 5

[terminal]
